/* Attribute generated bytes to source modules via the sourcemap mappings.
   For each generated segment we charge the bytes up to the next segment on
   the same line to that segment's source file. */
import fs from "node:fs"; import path from "node:path";
const B64="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const D=new Map([...B64].map((c,i)=>[c,i]));
function decodeVLQ(seg){const out=[];let shift=0,value=0;for(const c of seg){const d=D.get(c);if(d===undefined)continue;const cont=d&32;value+=(d&31)<<shift;shift+=5;if(!cont){const neg=value&1;value>>=1;out.push(neg?-value:value);value=0;shift=0;}}return out;}
const files = process.argv.slice(2);
const totals = new Map();
let grand = 0;
for (const f of files) {
  const js = fs.readFileSync(f, "utf8");
  const map = JSON.parse(fs.readFileSync(f + ".map", "utf8"));
  const lines = js.split("\n");
  let srcIdx = 0;
  map.mappings.split(";").forEach((lineStr, lineNo) => {
    if (!lineStr) return;
    const lineLen = (lines[lineNo] || "").length + 1;
    const segs = lineStr.split(",").map(decodeVLQ);
    let genCol = 0;
    const points = [];
    for (const s of segs) { genCol += s[0]||0; if (s.length >= 4) { srcIdx += s[1]; points.push([genCol, srcIdx]); } else points.push([genCol, null]); }
    for (let i = 0; i < points.length; i++) {
      const [col, si] = points[i];
      const end = i + 1 < points.length ? points[i+1][0] : lineLen;
      const bytes = Math.max(0, end - col);
      grand += bytes;
      const name = si === null ? "(unmapped)" : (map.sources[si] || "(?)");
      totals.set(name, (totals.get(name) || 0) + bytes);
    }
  });
}
const rows = [...totals].sort((a,b)=>b[1]-a[1]);
console.log(`attributed ${(grand/1024).toFixed(1)} KiB across ${rows.length} sources\n`);
// group by package / area
const groups = new Map();
for (const [src, n] of rows) {
  let g = src;
  const m = src.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
  if (m) g = "npm:" + m[1];
  else if (src.includes("/src/")) g = "app:src" ;
  else if (src.includes("/solid/")) g = "app:solid";
  groups.set(g, (groups.get(g)||0) + n);
}
console.log("BY PACKAGE/AREA:");
for (const [g,n] of [...groups].sort((a,b)=>b[1]-a[1])) console.log(String((n/1024).toFixed(1)).padStart(8)+"K  "+g);
console.log("\nTOP 30 SOURCE FILES:");
for (const [s,n] of rows.slice(0,30)) console.log(String((n/1024).toFixed(1)).padStart(8)+"K  "+s.replace(/^.*node_modules\//,"nm/"));
