/* Generated by scripts/generate-service-worker.mjs. */
const CACHE_PREFIX = "mabis-offline-";
const SHELL_CACHE = CACHE_PREFIX + "shell-9c20940e639a";
const RUNTIME_CACHE = CACHE_PREFIX + "runtime-9c20940e639a";
const PRECACHE_URLS = [
  "/index.html",
  "/manifest.json",
  "/fonts/gnu-freefont/FreeMono.woff2?v=2",
  "/fonts/gnu-freefont/FreeMonoBold.woff2?v=2",
  "/assets/index-nE3AC3N6.js",
  "/assets/index-Dni_i1ax.css",
  "/assets/Home-DM9ZtZws.js",
  "/assets/usePresence-BKnD4OXf.js",
  "/assets/arrow-up-right-CqnZhJ_U.js",
  "/assets/Icon-BoO7lgUR.js",
  "/assets/themes-CKWLcbHE.js",
  "/assets/pride-Jwj8n100.js",
  "/assets/palette-CT7-HgIL.js",
  "/assets/check-BXmRGr5x.js",
  "/assets/save-CIecGiPh.js",
  "/assets/star-D8r-cNiT.js",
  "/assets/trash-2-BM9ascgh.js",
  "/assets/IdleMount-Byn_urrB.js",
  "/assets/format-i5OvjDgx.js",
  "/assets/x-DailTPIl.js",
  "/assets/page-chrome-BedNA2Hs.js",
  "/assets/plus-C8xMGIng.js",
  "/assets/chevron-down-B_X9irjI.js",
  "/assets/prefs-C6lcbJyk.js",
  "/assets/SettingsModal-p9yUUYqF.js",
  "/assets/font-catalog-BvCrnvDm.js",
  "/assets/dialog-CPJA_2Ve.js",
  "/assets/index-JbX2uz7s.js",
  "/assets/search-B8W6NfYk.js",
  "/assets/MabisAIAssistant-BVVEPNwG.js",
  "/assets/geminiClient-BVqZFwhM.js",
  "/assets/weeks-B7cnPmm4.js",
  "/assets/isFriday-CngpKXdZ.js",
  "/assets/nextFriday-D07-J7ny.js",
  "/assets/maximize-2-C73sV4id.js",
  "/assets/minimize-2-D-kPG_IG.js",
  "/assets/send-5CD0O7z8.js",
  "/assets/FeedbackWidget-D1egQ95C.js",
  "/assets/image-plus-Cixd0YfP.js",
  "/assets/loader-circle-BMYQD4In.js",
  "/assets/ProfileEditor-BX5JeGkM.js",
  "/assets/rotate-ccw-clock-O-iS2GSJ.js",
  "/assets/JobReminder-CSPtWrP0.js",
  "/assets/QuickStartGuide-BStCQICj.js",
  "/assets/LunchMenuWidget-OVEy7e_i.js",
  "/assets/ScheduleWidget-D6xgQ1It.js",
  "/assets/ui-BNq31JXP.js",
  "/assets/link-2-C1ylAykX.js",
  "/assets/pencil-Dwcz5Woj.js",
  "/assets/JobsWidget-llyYCwj1.js",
  "/assets/names-Be6cvtAd.js",
  "/assets/startOfMonth-BCuJEmTi.js",
  "/assets/user-plus-BGFDZTWE.js",
  "/assets/select-CrADOY-4.js",
  "/assets/circle-check-HPE4eRVp.js",
  "/assets/DiscussionWidget-CETjlZ0W.js",
  "/assets/chevron-left-MOqVuBH1.js",
  "/assets/chevron-right-U2k-0_E2.js",
  "/assets/pause-DgtayzcF.js",
  "/assets/CalendarWidget-CepWfnW0.js",
  "/assets/AnnouncementsWidget-CPDxExj5.js",
  "/assets/image-DmB8No7D.js",
  "/assets/video-CI-4FEg2.js",
  "/assets/NewsWidget-CGqbgc0C.js",
  "/assets/MeetingModeWidget-UMrg-OEg.js",
  "/assets/undo-2-Bp4fgc7m.js",
  "/assets/MissingItemsWidget-CYaobBbN.js",
  "/assets/MembersWidget-uA3UfeF2.js",
  "/assets/users-DYUDxQRM.js",
  "/assets/offline-cache-Dc0LPn_a.js"
];
const MAX_RUNTIME_ENTRIES = 48;

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((name) => name.startsWith(CACHE_PREFIX) && name !== SHELL_CACHE && name !== RUNTIME_CACHE)
        .map((name) => caches.delete(name)),
    );
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable();
    }
    await self.clients.claim();
  })());
});

async function trim(cache, limit) {
  const keys = await cache.keys();
  const overflow = keys.length - limit;
  if (overflow > 0) {
    await Promise.all(keys.slice(0, overflow).map((request) => cache.delete(request)));
  }
}

async function appShellNavigation(event) {
  const shell = await caches.open(SHELL_CACHE);
  try {
    const preloaded = await event.preloadResponse;
    if (preloaded?.ok) {
      const type = preloaded.headers.get("content-type") || "";
      if (type.includes("text/html")) await shell.put("/index.html", preloaded.clone());
      return preloaded;
    }

    const response = await fetch(event.request);
    if (response.ok && (response.headers.get("content-type") || "").includes("text/html")) {
      await shell.put("/index.html", response.clone());
    }
    return response;
  } catch {
    return (await shell.match("/index.html")) || Response.error();
  }
}

async function staticAsset(request) {
  const cached = await caches.match(request, { ignoreSearch: true });
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok && response.type === "basic") {
    const runtime = await caches.open(RUNTIME_CACHE);
    await runtime.put(request, response.clone());
    await trim(runtime, MAX_RUNTIME_ENTRIES);
  }
  return response;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Authenticated Base44 data is deliberately never placed in Cache Storage.
  if (
    url.pathname.startsWith("/api/") ||
    url.pathname.startsWith("/functions/") ||
    request.headers.has("authorization")
  ) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(appShellNavigation(event));
    return;
  }

  if (
    url.pathname.startsWith("/assets/") ||
    url.pathname.startsWith("/fonts/") ||
    ["script", "style", "font", "image"].includes(request.destination)
  ) {
    event.respondWith(staticAsset(request));
  }
});
