/* Generated by scripts/generate-service-worker.mjs. */
const CACHE_PREFIX = "mabis-offline-";
const SHELL_CACHE = CACHE_PREFIX + "shell-6b3bec75cb91";
const RUNTIME_CACHE = CACHE_PREFIX + "runtime-6b3bec75cb91";
const PRECACHE_URLS = [
  "/index.html",
  "/manifest.json",
  "/fonts/gnu-freefont/FreeMono.woff2?v=2",
  "/fonts/gnu-freefont/FreeMonoBold.woff2?v=2",
  "/assets/index-CqqeDwSi.js",
  "/assets/index-Cd95ZQ_L.css",
  "/assets/Home-nlDgJ-EX.js",
  "/assets/usePresence-rN777ZoW.js",
  "/assets/arrow-up-right-TRNSGYy1.js",
  "/assets/Icon-C3iutHoP.js",
  "/assets/themes-CfQ3r0FR.js",
  "/assets/pride-Jwj8n100.js",
  "/assets/palette-BJ6L28kI.js",
  "/assets/check-CZrGc1_C.js",
  "/assets/save-BHv9oJ0z.js",
  "/assets/star-CekG5i_3.js",
  "/assets/trash-2-BkMMkWbq.js",
  "/assets/IdleMount-UM3yaYos.js",
  "/assets/format-i5OvjDgx.js",
  "/assets/x-DKQD_5M7.js",
  "/assets/page-chrome-QMm_GGQD.js",
  "/assets/plus-pt1kmQtl.js",
  "/assets/SettingsModal-CK0Jx7-y.js",
  "/assets/font-catalog-BvCrnvDm.js",
  "/assets/dialog-Biw6w62E.js",
  "/assets/index-BPJKMsJw.js",
  "/assets/search-Bet3cdWk.js",
  "/assets/MabisAIAssistant-CuruOdxg.js",
  "/assets/geminiClient-BVqZFwhM.js",
  "/assets/weeks-D7NtaTEP.js",
  "/assets/isFriday-CngpKXdZ.js",
  "/assets/nextFriday-D07-J7ny.js",
  "/assets/maximize-2-gFSAYhhC.js",
  "/assets/minimize-2-DdAGrFD5.js",
  "/assets/send-CYtUqwW7.js",
  "/assets/FeedbackWidget-CZFfUNPa.js",
  "/assets/image-plus-CbD1EmiZ.js",
  "/assets/loader-circle-BLso0cQt.js",
  "/assets/ProfileEditor-DJ4h9hIA.js",
  "/assets/rotate-ccw-clock-B1AkFoVl.js",
  "/assets/JobReminder-CTmU7ssz.js",
  "/assets/QuickStartGuide-DQOMl2nE.js",
  "/assets/LunchMenuWidget-C5VvuI_B.js",
  "/assets/ScheduleWidget-BCkXdeYh.js",
  "/assets/ui-CWtzMH4J.js",
  "/assets/link-2-iVlCqF0m.js",
  "/assets/pencil-DirBOdFC.js",
  "/assets/JobsWidget-DO08rEeD.js",
  "/assets/names-Be6cvtAd.js",
  "/assets/startOfMonth-BCuJEmTi.js",
  "/assets/user-plus-CuneoPmA.js",
  "/assets/select-CuFInY5j.js",
  "/assets/chevron-down-LXDLasKu.js",
  "/assets/circle-check-k3WHrxZT.js",
  "/assets/DiscussionWidget-DMYtlLVk.js",
  "/assets/chevron-left-CNZUV3r3.js",
  "/assets/chevron-right-CoJIbGrm.js",
  "/assets/pause-m1oGovm-.js",
  "/assets/CalendarWidget-BbP-4P0M.js",
  "/assets/AnnouncementsWidget-BYGgZiUX.js",
  "/assets/image-B1ZteBtD.js",
  "/assets/video-BRdKbT1M.js",
  "/assets/NewsWidget-B-azd4Yd.js",
  "/assets/MeetingModeWidget-BKUjvIOz.js",
  "/assets/undo-2-DPrYze-M.js",
  "/assets/MissingItemsWidget-DUjTYB7f.js",
  "/assets/MembersWidget-BXyOKOcD.js",
  "/assets/users-BtjqutcG.js",
  "/assets/offline-cache-nKnWf3MP.js"
];
const MAX_RUNTIME_ENTRIES = 48;

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((name) => name.startsWith(CACHE_PREFIX) && name !== SHELL_CACHE && name !== RUNTIME_CACHE)
        .map((name) => caches.delete(name)),
    );
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable();
    }
    await self.clients.claim();
  })());
});

async function trim(cache, limit) {
  const keys = await cache.keys();
  const overflow = keys.length - limit;
  if (overflow > 0) {
    await Promise.all(keys.slice(0, overflow).map((request) => cache.delete(request)));
  }
}

async function appShellNavigation(event) {
  const shell = await caches.open(SHELL_CACHE);
  try {
    const preloaded = await event.preloadResponse;
    if (preloaded?.ok) {
      const type = preloaded.headers.get("content-type") || "";
      if (type.includes("text/html")) await shell.put("/index.html", preloaded.clone());
      return preloaded;
    }

    const response = await fetch(event.request);
    if (response.ok && (response.headers.get("content-type") || "").includes("text/html")) {
      await shell.put("/index.html", response.clone());
    }
    return response;
  } catch {
    return (await shell.match("/index.html")) || Response.error();
  }
}

async function staticAsset(request) {
  const cached = await caches.match(request, { ignoreSearch: true });
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok && response.type === "basic") {
    const runtime = await caches.open(RUNTIME_CACHE);
    await runtime.put(request, response.clone());
    await trim(runtime, MAX_RUNTIME_ENTRIES);
  }
  return response;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Authenticated Base44 data is deliberately never placed in Cache Storage.
  if (
    url.pathname.startsWith("/api/") ||
    url.pathname.startsWith("/functions/") ||
    request.headers.has("authorization")
  ) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(appShellNavigation(event));
    return;
  }

  if (
    url.pathname.startsWith("/assets/") ||
    url.pathname.startsWith("/fonts/") ||
    ["script", "style", "font", "image"].includes(request.destination)
  ) {
    event.respondWith(staticAsset(request));
  }
});
