/* Generated by scripts/generate-service-worker.mjs. */
const CACHE_PREFIX = "mabis-offline-";
const SHELL_CACHE = CACHE_PREFIX + "shell-ab1bfc8247ee";
const RUNTIME_CACHE = CACHE_PREFIX + "runtime-ab1bfc8247ee";
const LAYOUT_CACHE = CACHE_PREFIX + "layout-ab1bfc8247ee";
const PRECACHE_URLS = [
  "/index.html",
  "/manifest.json",
  "/fonts/gnu-freefont/FreeMono-subset.woff2?v=3",
  "/fonts/gnu-freefont/FreeMonoBold-subset.woff2?v=3",
  "/assets/index-DQxyqCND.js",
  "/assets/index-DVK_B-I-.css",
  "/assets/Home-BWcNNKtB.js",
  "/assets/format-i5OvjDgx.js",
  "/assets/Icon-ubblPVzZ.js",
  "/assets/x-BcMW47sZ.js",
  "/assets/chevron-down-DvOCqg1Q.js",
  "/assets/prefs-CmMiL98n.js",
  "/assets/usePresence-B_k3T73q.js",
  "/assets/themes-C1-G6ymG.js",
  "/assets/pride-COm4K_zG.js",
  "/assets/palette-CiPQ6ChO.js",
  "/assets/check-z3oGYa0D.js",
  "/assets/save-wUYTRrf5.js",
  "/assets/search-BKxaFEnk.js",
  "/assets/star-inYpULrp.js",
  "/assets/trash-2-w6s5z3lS.js",
  "/assets/IdleMount-C5eaqFGJ.js",
  "/assets/SettingsModal-DYUn5Alp.js",
  "/assets/font-catalog-BYY-PY3D.js",
  "/assets/dialog-Chs9x7wD.js",
  "/assets/index-n4sQszxn.js",
  "/assets/lock-BvWsb6ZT.js",
  "/assets/StyleWelcomeDialog-m93J2A_3.js",
  "/assets/FeedbackWidget-Bjdsl6IK.js",
  "/assets/loader-circle-d3CcGKuD.js",
  "/assets/ProfileEditor-KT7iI9YO.js",
  "/assets/rotate-ccw-clock-Cjb90Y4D.js",
  "/assets/JobReminder-Xzb-vxAf.js",
  "/assets/weeks-B7cnPmm4.js",
  "/assets/isFriday-CngpKXdZ.js",
  "/assets/nextFriday-D07-J7ny.js",
  "/assets/QuickStartGuide-BoNvOF73.js",
  "/assets/LunchMenuWidget-_wwQEQcS.js",
  "/assets/ScheduleWidget-hP3owWSB.js",
  "/assets/ui-CEe5b5H8.js",
  "/assets/link-2-C_BRh6wr.js",
  "/assets/pencil-CIs-EUJQ.js",
  "/assets/JobsWidget-CminDqSF.js",
  "/assets/names-Be6cvtAd.js",
  "/assets/startOfMonth-BCuJEmTi.js",
  "/assets/user-plus-oBdBB2w1.js",
  "/assets/select-DdZV4NX_.js",
  "/assets/circle-check-CLroTruv.js",
  "/assets/maximize-2-Bqie4A_4.js",
  "/assets/plus-BR6uyh5D.js",
  "/assets/DiscussionWidget-CwmLaE6t.js",
  "/assets/chevron-left-CiO9X9RE.js",
  "/assets/chevron-right-BUOeBv1o.js",
  "/assets/pause-CO4u9UCp.js",
  "/assets/CalendarWidget-CFyjz3h_.js",
  "/assets/AnnouncementsWidget-DWgt-F61.js",
  "/assets/image-C0qnyI34.js",
  "/assets/video-BTG8tOVT.js",
  "/assets/NewsWidget-BI9g1Dkv.js",
  "/assets/MeetingModeWidget-BNvdJTlq.js",
  "/assets/arrow-right-C0QQssUK.js",
  "/assets/undo-2-vhN5SDhH.js",
  "/assets/MissingItemsWidget-BZMwPk1O.js",
  "/assets/MembersWidget-b_mFlCQF.js",
  "/assets/users-u3M_JVVt.js",
  "/assets/offline-cache-CPMF3Un_.js"
];
/* Assets only the boss Home layout executes. Not in the install precache: the
   default layout would pay to download and store code it never runs. */
const BOSS_LAYOUT_URLS = [
  "/assets/boss-DeDBR6uf.js",
  "/assets/boss-BivFLuJ-.css",
  "/assets/glass-Dg20RSkI.css",
  "/assets/arrow-up-right-DZfvjpM1.js",
  "/assets/page-chrome-Bu3csQI3.js",
  "/assets/ScrollVelocity-BGna_5tK.js",
  "/assets/ScrollScaleRitual-DPvzPfvm.js"
];
const MAX_RUNTIME_ENTRIES = 48;

self.addEventListener("install", (event) => {
  /*
   * Keep a new build waiting while an older build still controls an open tab.
   * That preserves the exact hashed chunks the active meeting/document loaded
   * and avoids an unrequested reload. The update activates naturally after
   * the last old tab closes, so the next normal visit gets the new shell.
   */
  event.waitUntil(caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((name) => name.startsWith(CACHE_PREFIX)
          && name !== SHELL_CACHE && name !== RUNTIME_CACHE && name !== LAYOUT_CACHE)
        .map((name) => caches.delete(name)),
    );
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable();
    }
    await self.clients.claim();
  })());
});

/*
 * Cache exactly one layout's assets: whichever one the reader is using.
 *
 * The page posts this on boot and on every change, so switching to the boss
 * layout fetches its chunks into the offline shell, and switching back deletes
 * them rather than leaving a layout in storage that is no longer rendered.
 */
async function applyLayout(layout) {
  const cache = await caches.open(LAYOUT_CACHE);
  if (layout === "boss") {
    /*
     * addAll() is all-or-nothing: if one URL in BOSS_LAYOUT_URLS 404s or hits
     * a transient network error, the whole call rejects, meaning NONE of the
     * URLs get cached — including glass.css, even though every other boss
     * chunk fetched fine. One flaky request then quietly costs the whole
     * layout its offline cache, so the next boss-layout paint (or the first
     * one after an interrupted connection) has nothing to fall back on.
     * Caching each URL independently means one failure only ever costs that
     * one file.
     */
    await Promise.all(BOSS_LAYOUT_URLS.map((url) =>
      cache.add(url).catch(() => {})
    ));
    return;
  }
  await Promise.all(BOSS_LAYOUT_URLS.map((url) => cache.delete(url)));
}

self.addEventListener("message", (event) => {
  if (event.data?.type !== "mabis-home-layout") return;
  // Never let a cache write fail the message: an offline switch just means the
  // chunks are fetched on demand the next time the layout renders.
  event.waitUntil(applyLayout(event.data.layout).catch(() => {}));
});

async function trim(cache, limit) {
  const keys = await cache.keys();
  const overflow = keys.length - limit;
  if (overflow > 0) {
    await Promise.all(keys.slice(0, overflow).map((request) => cache.delete(request)));
  }
}

async function appShellNavigation(event) {
  const shell = await caches.open(SHELL_CACHE);
  try {
    const preloaded = await event.preloadResponse;
    if (preloaded?.ok) {
      const type = preloaded.headers.get("content-type") || "";
      if (type.includes("text/html")) await shell.put("/index.html", preloaded.clone());
      return preloaded;
    }

    const response = await fetch(event.request);
    if (response.ok && (response.headers.get("content-type") || "").includes("text/html")) {
      await shell.put("/index.html", response.clone());
    }
    return response;
  } catch {
    return (await shell.match("/index.html")) || Response.error();
  }
}

/* Prefixes, not a regex. This file is emitted from a template literal, so any
   backslash in it is an escape sequence for the GENERATOR first — a regex
   literal here silently lost its / and shipped a worker that would not parse.
   Plain string prefixes have nothing to escape. */
const DEV_SERVER_PREFIXES = ["/@vite/", "/@id/", "/@fs/", "/node_modules/", "/src/", "/solid/"];

async function staticAsset(request) {
  const cached = await caches.match(request, { ignoreSearch: true });
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response.ok && response.type === "basic") {
      const runtime = await caches.open(RUNTIME_CACHE);
      await runtime.put(request, response.clone());
      await trim(runtime, MAX_RUNTIME_ENTRIES);
    }
    return response;
  } catch (error) {
    /*
     * The network failed and this is not in the cache.
     *
     * This used to fall straight through as a rejected promise, and a
     * rejection inside respondWith() makes the browser fail the resource
     * OUTRIGHT — no retry, no fallback to the network it would have used
     * without a worker. For a stylesheet that reads as "the CSS randomly did
     * not load": the page renders unstyled with nothing in the console
     * pointing at the worker.
     *
     * Try the cache once more, ignoring Vary this time — a stale copy of a
     * hashed asset is always better than none. Only if that misses does the
     * error propagate, and then it is the browser's own network error rather
     * than one this worker manufactured.
     */
    const stale = await caches.match(request, { ignoreSearch: true, ignoreVary: true });
    if (stale) return stale;
    throw error;
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  /*
   * Never touch the dev server.
   *
   * A worker installed by an earlier PRODUCTION visit keeps controlling this
   * origin, and the Base44 preview serves the app from Vite's dev server on
   * that same origin. Those module URLs (/@vite/, /@fs/, /src/, HMR "?t="
   * stamps) exist in no build this worker has ever cached, so every one was a
   * guaranteed cache miss handed to a network fetch that fails the instant the
   * dev server reloads — which is constantly. The result is stylesheets and
   * chunks that intermittently do not arrive, in the preview only, with the
   * built site working perfectly.
   *
   * Returning early leaves them to the browser, which is what a worker that
   * knows nothing about them should have done from the start.
   */
  if (DEV_SERVER_PREFIXES.some((prefix) => url.pathname.startsWith(prefix)) || url.searchParams.has("t")) {
    return;
  }

  // Authenticated Base44 data is deliberately never placed in Cache Storage.
  if (
    url.pathname.startsWith("/api/") ||
    url.pathname.startsWith("/functions/") ||
    request.headers.has("authorization")
  ) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(appShellNavigation(event));
    return;
  }

  if (
    url.pathname.startsWith("/assets/") ||
    url.pathname.startsWith("/fonts/") ||
    ["script", "style", "font", "image"].includes(request.destination)
  ) {
    event.respondWith(staticAsset(request));
  }
});
