/**
 * Perceptual colour engine (OKLab / OKLCh).
 *
 * Theme derivatives — surfaces, muted fills, borders, text-safe accents — are
 * generated by moving lightness and chroma in OKLCh, where equal steps look
 * equal to the eye. Deriving them in HSL (as the older themes did) shifts hue
 * and collapses chroma unevenly, which is why flag colours used to turn muddy
 * the moment they were tinted.
 *
 * Everything returns "H S% L%" strings, because the app's tokens are consumed
 * as hsl(var(--token)) — the maths is perceptual, the output stays compatible.
 */

const f = (x) => (x >= 0.0031308 ? 1.055 * Math.pow(x, 1 / 2.4) - 0.055 : 12.92 * x);
const fInv = (x) => (x >= 0.04045 ? Math.pow((x + 0.055) / 1.055, 2.4) : x / 12.92);
const clamp01 = (v) => Math.min(1, Math.max(0, v));

function linearToOklab(r, g, b) {
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

function oklabToLinear(L, a, b) {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

export function hexToOklch(hex) {
  const h = hex.replace("#", "");
  const r = fInv(parseInt(h.slice(0, 2), 16) / 255);
  const g = fInv(parseInt(h.slice(2, 4), 16) / 255);
  const b = fInv(parseInt(h.slice(4, 6), 16) / 255);
  const [L, A, B] = linearToOklab(r, g, b);
  return { L, C: Math.hypot(A, B), h: (Math.atan2(B, A) * 180) / Math.PI };
}

function toRgb(L, C, hDeg) {
  const rad = (hDeg * Math.PI) / 180;
  const [r, g, b] = oklabToLinear(L, C * Math.cos(rad), C * Math.sin(rad));
  return [r, g, b];
}

const inGamut = ([r, g, b]) => [r, g, b].every((v) => v >= -0.0005 && v <= 1.0005);

/** Reduce chroma — never lightness or hue — until the colour is displayable. */
function fit(L, C, h) {
  if (inGamut(toRgb(L, C, h))) return toRgb(L, C, h);
  let lo = 0, hi = C;
  for (let i = 0; i < 18; i++) {
    const mid = (lo + hi) / 2;
    if (inGamut(toRgb(L, mid, h))) lo = mid; else hi = mid;
  }
  return toRgb(L, lo, h);
}

export function oklchToHex(L, C, h) {
  const [r, g, b] = fit(L, C, h).map((v) => Math.round(clamp01(f(v)) * 255));
  const hx = (v) => v.toString(16).padStart(2, "0");
  return `#${hx(r)}${hx(g)}${hx(b)}`;
}

/** OKLCh → the "H S% L%" triple the app's CSS tokens expect. */
export function oklchToHsl(L, C, hue) {
  const [lr, lg, lb] = fit(L, C, hue).map((v) => clamp01(f(v)));
  const max = Math.max(lr, lg, lb), min = Math.min(lr, lg, lb);
  const l = (max + min) / 2;
  let h = 0, s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === lr) h = (lg - lb) / d + (lg < lb ? 6 : 0);
    else if (max === lg) h = (lb - lr) / d + 2;
    else h = (lr - lg) / d + 4;
    h *= 60;
  }
  return `${Math.round(h)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

/** Re-light a source colour: keep its hue, place it at a chosen L / C. */
export function tone(hex, L, cScale = 1, cMax = 0.2) {
  const c = hexToOklch(hex);
  return oklchToHsl(L, Math.min(c.C * cScale, cMax), c.h);
}

export function toneHex(hex, L, cScale = 1, cMax = 0.2) {
  const c = hexToOklch(hex);
  return oklchToHex(L, Math.min(c.C * cScale, cMax), c.h);
}

/** A neutral surface carrying a whisper of the theme's hue. */
export function surface(hex, L, C = 0.008) {
  return oklchToHsl(L, C, hexToOklch(hex).h);
}